
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - ./data:/app/data
    environment:
      - GF_PLUGINS_PREINSTALL=frser-sqlite-datasource
    restart: unless-stopped
    depends_on:
      - api

volumes:
  grafana_data:
